project:
  type: website
  output-dir: docs

website:
  title: "DSCI 542 Lab 2"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/danishkarlin
      - icon: github
        href: https://github.com/mdkbmi
format:
  html:
    theme: cosmo
    css: styles.css



