---
title: "Using machine learning to predict quality of cars"
author: "Danish Karlin Isa"
date: "2025-01-18"
---

Buying a new car can be an exciting yet tiresome experience.
In today's market, many of us are spoilt for choices when looking for a new car.
Whether you are a family person with lots of people and stuff to haul,
an outdoor junkie who frequently ventures off the beaten track,
or if you just want something that makes your daily commute less stressful,
there's bound to be a car that suits your needs.

Being spoilt for choice is definitely a much more preferable problem to have
over having very few options. 
However, it can be a little overwhelming and time-consuming 
to properly evaluate every available car if you're looking to buy one.
Recently, while I was going through so many reviews and brochures in hopes of
finding the right car for myself, it struck me —
what if I can leverage machine learning to make the process easier?

# What is machine learning?

Machine learning is all about using computers to spot patterns in large amounts of data,
which can then be used to make predictions about similar situations in the future.
In fact, many of the applications that we use leverage machine learning
to make our lives better, 
such as Netflix's recommendations for shows and movies and spam email detection.

By using machine learning, we can let computers do the heavy lifting for us by
analysing traits of desirable and undesirable cars from past data,
helping us shortlist cars that meet our specific requirements.
This results in a smaller pool of cars for us to consider,
which saves us time spent on visiting dealerships and test drives,
and reduces the effort needed to sift through numerous car reviews.